
return {
    DeletedWaypoints = "Unit Vehicles: Waypoints are deleted!",
    Errors = {
        AttachmentNotFound = "Unit Vehicles: attachment vehicle_feet_passenger0 is not found!",
        WaypointNotFound = "Unit Vehicles: Waypoint is not found!",
    },
    GeneratedWaypoints = "Unit Vehicles: Waypoints are generated!",
    LoadedWaypoints = "Unit Vehicles: Waypoints are restored!",
    OnDelete = "You are about to DELETE the waypoints.",
    OnGenerate = "You are about to GENERATE the waypoints.",
    OnLoad = "You are about to LOAD the waypoints.",
    OnSave = "You are about to SAVE the waypoints.",
    SavedWaypoints = "Unit Vehicles: Waypoints are saved!",
    SaveLoad_Cancel = "Cancel",
    SaveLoad_OK = "OK",
    Tools = {
        AlwaysDrawWaypoints = "Always draw waypoints",
        Bidirectional = "Bi-directional link",
        BidirectionalHelp = "Connect bi-directional link automatically.",
        Category = "GreatZenkakuMan's tools",
        Delete = "Delete waypoints",
        Description = "Create your own routes for vehicles!",
        DescriptionInMenu = "Create routes for Unit Vehicles.",
        DrawDistance = "Draw distance",
        DrawDistanceHelp = "The maximum distance to draw waypoints.",
        DrawWaypoints = "Draw waypoints",
        Generate = "Generate waypoints",
        Instructions = "Select a waypoint or a traffic light to link.  Select a vehicle driven by a Unit Vehicles to assign its waypoint group.",
        Left = {
            "Create a new waypoint.",
            "Select another waypoint you want to link to.  Select the same waypoint to remove it.",
        },
        LightLevel = {
            All = "Full lights",
            Headlights = "Running lights and headlights",
            None = "No light",
            Running = "Only running lights",
            Title = "Light level",
        },
        LockVehicle = "Lock vehicle",
        LockVehicleHelp = "If checked, Unit Vehicles prevents other players from getting in.",
        MaxSpeed = "Max speed [km/h]",
        Name = "Unit Vehicles Waypoint Tool",
        PrintName = "Unit Vehicles Waypoint Tool",
        Restore = "Restore waypoints",
        Right = {"Update waypoint."},
        Save = "Save waypoints",
        ServerSettings = "Server settings",
        ShowInfo = {
            Group = "Group: ",
            ID = "ID: ",
            SpeedLimit = "Speed limit [km/h]: ",
        },
        UpdateRadius = "Update radius",
        UpdateRadiusHelp = "Waypoints in this radius will be updated at a time when you press E + Right click.",
        WaypointGroup = "Waypoint group",
        WaypointGroupHelp = [[You can force Unit Vehicles to run along specified group of waypoints.
0 means all vehicles can go there.]],
    },
    UndoText = "Undone Unit Vehicles's waypoint",
    WireSupport = {
        ToolDesc = "Provides some data of Unit Vehicles's waypoints for use with the wire system.",
        ToolName = "[UV] Wire Waypoint Manager",
    },
}
