
return {
    DeletedWaypoints = "Unit Vehicles: ウェイポイントが削除されました!",
    Errors = {
        AttachmentNotFound = "Unit Vehicles: アタッチメント vehicle_feet_passenger0 が見つかりません!",
        WaypointNotFound = "Unit Vehicles: ウェイポイントが見つかりません!",
    },
    GeneratedWaypoints = "Unit Vehicles: ウェイポイントが生成されました!",
    LoadedWaypoints = "Unit Vehicles: ウェイポイントが読み込まれました!",
    OnDelete = "保存されたウェイポイントを削除します。",
    OnGenerate = "ウェイポイントの自動生成を行います。",
    OnLoad = "ウェイポイントの読み込みを行います。",
    OnSave = "ウェイポイントの保存を行います。",
    SavedWaypoints = "Unit Vehicles: ウェイポイントが保存されました!",
    SaveLoad_Cancel = "キャンセル",
    SaveLoad_OK = "OK",
    Tools = {
        AlwaysDrawWaypoints = "常にウェイポイントを表示する",
        Bidirectional = "双方向に接続",
        BidirectionalHelp = "自動的に双方向に接続します。",
        Category = "GreatZenkakuMan's tools",
        Delete = "ウェイポイントの削除",
        Description = "乗り物のために道を作ろう!",
        DescriptionInMenu = "Unit Vehiclesのためのルートを構築する。",
        DrawDistance = "描画距離",
        DrawDistanceHelp = "ウェイポイントを描画する最大の距離。",
        DrawWaypoints = "ウェイポイントを描画する",
        Generate = "ウェイポイントの生成",
        Instructions = "ウェイポイントや信号をクリックして接続する。または、Unit Vehiclesが運転する乗り物をクリックするとグループ番号を割り当てられる。",
        Left = {
            "新しいウェイポイントを作成する。",
            "接続したいウェイポイントをクリックする。同じものをもう一度クリックすると消去する。",
        },
        LightLevel = {
            All = "すべて",
            Headlights = "デイライトとヘッドライト",
            None = "無効",
            Running = "デイライトのみ",
            Title = "ライトのレベル"
        },
        LockVehicle = "車両をロックする",
        LockVehicleHelp = "チェックを入れると、他のプレイヤーがUnit Vehiclesの操縦する車両に乗れなくなる。",
        MaxSpeed = "最大速度 [km/h]",
        Name = "Unit Vehicles ウェイポイントツール",
        PrintName = "Unit Vehicles ウェイポイントツール",
        Restore = "ウェイポイントの読み込み",
        Right = {"ウェイポイントを更新する。"},
        Save = "ウェイポイントの保存",
        ServerSettings = "サーバー側の設定",
        ShowInfo = {
            Group = "グループ番号: ",
            ID = "ID: ",
            SpeedLimit = "最大速度 [km/h]: ",
        },
        UpdateRadius = "アップデートの適用半径",
        UpdateRadiusHelp = "E + 右クリックでこの範囲にあるウェイポイントが一度に更新される。",
        WaypointGroup = "グループ番号",
        WaypointGroupHelp = [[一部のUnit Vehiclesに対して向かうべき道を制限できる。
0にすると誰でも通れるウェイポイントになる。]],
    },
    UndoText = "Unit Vehiclesのウェイポイントを元に戻した",
    WireSupport = {
        ToolDesc = "Unit Vehiclesのウェイポイントに関する情報をWireが利用できるようにする。",
        ToolName = "[UV] Wire ウェイポイント マネージャ",
    },
}
