
return {
    DeletedWaypoints = "Unit Vehicles: Точки удалены!",
    Errors = {
        AttachmentNotFound = "Unit Vehicles: attachment vehicle_feet_passenger0 не найден!",
        WaypointNotFound = "Unit Vehicles: Точка не найден!",
    },
    GeneratedWaypoints = "Unit Vehicles: Точки сгенерировались!",
    LoadedWaypoints = "Unit Vehicles: Точки загружены!",
    OnDelete = "Вы собираетесь УДАЛИТЬ точки.",
    OnGenerate = "Вы собираетесь СГЕНЕРИРОВАТЬ точки.",
    OnLoad = "Вы собираетесь ЗАГРУЗИТЬ точки.",
    OnSave = "Вы собираетесь СОХРАНИТЬ точки.",
    SavedWaypoints = "Unit Vehicles: Точки сохранены!",
    SaveLoad_Cancel = "Отмена",
    SaveLoad_OK = "ОК",
    Tools = {
        AlwaysDrawWaypoints = "Постоянно отрисовывать точки",
        Bidirectional = "Bi-directional соединение",
        BidirectionalHelp = "Connect bi-directional link automatically.",
        Category = "GreatZenkakuMan's tools",
        Delete = "Удалить точки",
        Description = "Создайте свой маршрут для транспорта!",
        DescriptionInMenu = "Создать маршруты для Unit Vehicles",
        DrawDistance = "Дистанция отрисовки",
        DrawDistanceHelp = "Дистанция, на которой будут отрисовываться точки",
        DrawWaypoints = "Отображать точки",
        Generate = "Сгенерировать точки",
        Instructions = "Выберете точку и/или светофор чтобы соединить их.  Выберете транспорт управляемый Unit Vehicles, чтобы назначить ему группу.",
        Left = {
            "Создать новую точку.",
            "Выберите другую точку которую вы хотите соединить.  Выберите эту же точку чтобы удалить ее.",
        },
        LightLevel = {
            All = "Все фары",
            Headlights = "Ходовые и фары",
            None = "Без фар",
            Running = "Только ходовые",
            Title = "Уровень освещения",
        },
        LockVehicle = "Закрывать транспорт",
        LockVehicleHelp = "Закрывать транспорт при спавне?",
        MaxSpeed = "Максисальная скорость [км/ч]",
        Name = "Unit Vehicles Waypoint Tool",
        PrintName = "Unit Vehicles Waypoint Tool",
        Restore = "Загрузить точки",
        Right = {"Обновить точки."},
        Save = "Сохранить точки",
        ServerSettings = "Настройки сервера",
        ShowInfo = {
            Group = "Группа: ",
            ID = "ID: ",
            SpeedLimit = "Ограничение [км/ч]: ",
        },
        UpdateRadius = "Обновить радиус",
        UpdateRadiusHelp = "Точки в этом радиусе будут обновлены в то время, когда вы нажмете E + Правая Кнопка Мыши.",
        WaypointGroup = "Группа точки",
        WaypointGroupHelp = [[Вы можете разделить маршруты по группам.
0 значит, что все могут тут ездить.]],
    },
    UndoText = "Отмена точки",
}
